---
- name: NGINX
  hosts: webservers
  sudo: yes
  tasks:
    - name: Ensure dependencies are installed
      apt: name={{item}} update-cache=yes
      with_items:
        - curl
        - htop
        - lynx
        - vim
    - name: Ensure installed
      apt: pkg=nginx state=present
    - name: Ensure service started
      service: name=nginx state=started enabled=yes

