---
- name: MYSQL
  hosts: webservers
  sudo: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Install
      apt: name={{item}} state=present
            update_cache=yes cache_valid_time=90000
      with_items:
      - python-mysqldb   # for ansible mysql module
      - mysql-server
    - name: Ensure service is started
      service: name=mysql state=started enabled=yes
    - name: update root password for all root accounts
      mysql_user: name=root host={{item}} password={{root_db_passwd}} priv=*.*:ALL,GRANT
      with_items:
      - 127.0.0.1
      - ::1
      - localhost
    - name: copy .my.cnf file with root password credentials
      template: src=templates/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

